Issue 151: Add To Review slash command
SamirBoulil/slub pull request #153
Opened 2021-12-05 09:09 UTC by SamirBoulil

2021-12-11 20:17 UTC, SamirBoulil commented on config/routes.yaml
> +chat_slack_tr:
test

2021-12-12 13:25 UTC, samirapptesting approved these changes

2021-12-12 13:25 UTC, samirapptesting approved these changes

2021-12-12 13:35 UTC, samirapptesting requested changes
test

2021-12-12 13:38 UTC, samirapptesting requested changes
test

2021-12-12 13:38 UTC, samirapptesting approved these changes

2021-12-12 13:58 UTC, samirapptesting approved these changes
aze

2021-12-12 14:06 UTC, samirapptesting approved these changes
azeazeazeaze

2021-12-12 14:07 UTC, samirapptesting requested changes
azeazeaze

2021-12-12 14:07 UTC, samirapptesting requested changes
azeazeaze

2021-12-12 14:07 UTC, samirapptesting requested changes
azeazeaze

2021-12-12 15:35 UTC, samirapptesting requested changes
azeazeaze

2021-12-12 15:37 UTC, SamirBoulil commented on src/Slub/Application/Common/ChatClient.php
> +    public function acknowledgeRequest(string $url): void;
to remove

2021-12-12 15:38 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/APIHelper.php
> +    public static function checkStatusCodeSuccess(ResponseInterface $response): void
to test

2021-12-12 15:38 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/ChannelIdentifierHelper.php
> +        Assert::contains($channelIdentifier, self::SEPARATOR, 'Impossible to split channel identifier');
to test

2021-12-12 15:38 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/ProcessTRRequestListener.php
> +class ProcessTRRequestListener
Rename ProcessTRSubmissionListener

2021-12-12 15:39 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/ProcessTRRequestListener.php
> +class ProcessTRRequestListener
Add E2E tests for:
- no url
- URL correctly formatted but invalid PR Link (can't fetch details)
- Nominal: PR Submitted

2021-12-12 15:40 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/ProcessTRRequestListener.php
> +class ProcessTRRequestListener
Consider, Reorganizing infra/chat/slack/* with sub directories (oAuth, TR submission, common, client ?)

2021-12-12 15:42 UTC, SamirBoulil commented on src/Slub/Infrastructure/Chat/Slack/SlubBot.php
> +//        $bot->hears('.*TR.*<https://github.com/(.*)/pull/(\d+).*>.*$', $createNewPr);
uncomment before merging

2021-12-12 15:43 UTC, SamirBoulil commented on src/Slub/Infrastructure/VCS/Github/Query/GetPRInfo.php
> +        $breakout = GithubAPIHelper::breakoutPRIdentifier($PRIdentifier);
remove breakout and introduce 2 different methods

2021-12-18 15:47 UTC, samirapptesting approved these changes
azeaze

2021-12-18 18:31 UTC, samirapptesting reviewed
azeaze

2021-12-18 18:31 UTC, samirapptesting approved these changes
azeaze

2021-12-18 18:32 UTC, samirapptesting requested changes
azeaze

2021-12-18 18:59 UTC, SamirBoulil commented on tests/Integration/Infrastructure/Chat/Slack/TR/ProcessTRAsyncTest.php
> +//        $this->chatClientSpy->assertPublishMessageWithBlocksInChannelContains('team_123@channel_name', 'https://github.com/SamirBoulil/slub/pull/153');
uncomment

2021-12-19 11:33 UTC, samirapptesting reviewed
azeaze

2021-12-19 11:33 UTC, samirapptesting approved these changes
azeaze

2021-12-19 11:33 UTC, samirapptesting requested changes
azeaze

2021-12-19 11:35 UTC, samirapptesting reviewed
aze

2021-12-19 11:36 UTC, samirapptesting approved these changes
azeaze

2021-12-19 11:50 UTC, merged